#!/bin/sh
# Based on ufetch-debian
# https://gitlab.com/jschx/ufetch/-/blob/master/ufetch-debian

esc=""
black="${esc}[30m"
red="${esc}[31m"
green="${esc}[32m"
yellow="${esc}[33m"
blue="${esc}[34m"
magenta="${esc}[35m"
cyan="${esc}[36m"
white="${esc}[37m"
reset="${esc}[0m"

# you can change these
ic="${reset}"                       # info
c0="${reset}${red}"
c1="${reset}${green}"
c2="${reset}${yellow}"
c3="${reset}${blue}"
c4="${reset}${magenta}"
c5="${reset}${cyan}"

## OUTPUT

cat <<EOF

${c0}     ,---._	${c1}     ,---._ 	${c2}     ,---._	${c3}     ,---._	${ic}
${c0}   /\`  __  \\	${c1}   /\`  __  \\	${c2}   /\`  __  \\	${c3}   /\`  __  \\	${ic}
${c0}  |   /    |	${c1}  |   /    |	${c2}  |   /    |	${c3}  |   /    |	${ic}
${c0}  |   \`.__.\`	${c1}  |   \`.__.\`	${c2}  |   \`.__.\`	${c3}  |   \`.__.\`	${ic}
${c0}   \        	${c1}   \        	${c2}   \       	${c3}   \       	${ic}
${c0}    \`-,_    	${c1}    \`-,_   	${c2}    \`-,_  	${c3}    \`-,_  	${ic}

EOF
