#!/bin/sh
# ANSI color scheme script by github.com/joshdk https://github.com/joshdk/hedgehogs
red=$(printf '\e[31m')
grn=$(printf '\e[32m')
ylw=$(printf '\e[33m')
blu=$(printf '\e[34m')
mag=$(printf '\e[35m')
cya=$(printf '\e[36m')

bld=$(printf '\e[1m')
rst=$(printf '\e[0m')

cat << ART

$red   ╷╽╽╽╽╽╽╽╽╽╷     $grn    ╷╽╽╽╽╽╽╽╽╽╷    $ylw   ╷╽╽╽╽╽╽╽╽╽╷
$red  ╽┃┃┃┃┃┃┃┃┃┃┃╽    $grn   ╽┃┃┃┃┃┃┃┃┃┃┃╽   $ylw  ╽┃┃┃┃┃┃┃┃┃┃┃╽
$red ┪┃┃┃┃┃┃┃┃┃┃' .\   $grn  /. '✿┃┃┃┃┃┃┃┃┃┢  $ylw ┪┃┃┃┃┃┃┃┃┃┃' .\
$red  ╹┃┃┃┃┃┃┃┃⧓ ___•  $grn •___ ┃┃┃┃┃┃┃┃┃╹   $ylw  ╹┃┃┃┃┃┃┃┃⧓ ___•
$rst
ART
