# Editor completions
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
continuation_prompt = '[▶](bright-black) '
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
${custom.gitsymbol}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$sudo\
$netns\
${custom.ansible}\
$fill\
$cmd_duration\
$os\
$time\
$shell\
$container\
$status\
$line_break\
$jobs\
$battery\
$character"""

[fill]
symbol = ' '
style = ''

[character]
# success_symbol = '[ ➜](bold green)'
# error_symbol = '[ ](bold red)'
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[username]
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
format = '[@$hostname $ssh_symbol]($style)'

[git_status]
ignore_submodules = true

[mise]
disabled = false

[sudo]
disabled = false
format = '[$symbol]($style)'

[cmd_duration]
show_milliseconds = true

[time]
disabled = false
format = '[$time]($style) '
time_format = '%F %r'

[status]
disabled = false
format = '[$symbol $status]($style) '
symbol = ''

[os]
disabled = false
format = '[$symbol$type(:$codename)]($style) '

[shell]
disabled = false
style = "cyan bold"
bash_indicator = ''
fish_indicator = '󰈺'
zsh_indicator = ''
powershell_indicator = ''
cmd_indicator = ''
unknown_indicator = "unk"

[custom.ansible]
description = "Ansible version"
command = "echo -n $(ansible-community --version 2>/dev/null | grep -i ^ansible | awk '{ print $NF }')"
when = """ test -n "${ANSIBLE_HOME}" """
files = [ "ansible.cfg" ]
shell = "/bin/bash"
symbol = " "
format = "[$symbol$output]($style) "

[custom.gitsymbol]
description = "Display symbol for remote Git server"
command = "git-remote-symbol"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
shell = ["bash", "--noprofile", "--norc"]
format = "$output "
ignore_timeout = true

[os.symbols]
AIX = " "
Alpaquita = " "
AlmaLinux = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
Bluefin = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = " "
Illumos = " "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = "󰣭 "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = "  "
Windows = " "
