[settings]
cargo.binstall = true
go_default_packages_file = "~/.config/mise/default-golang-packages"
node.compile = false
node.gpg_verify = false
npm.bun = true
pipx.uvx = true
python.default_packages_file = "~/.config/mise/default-python-packages"
python.uv_venv_auto = true
ruby.default_packages_file = "~/.config/mise/default-ruby-packages"
# disable_backends = ["asdf"]

[alias.node.versions]
lts = "22"
lts-jod = "22"
lts-iron = "20"
lts-hydrogen = "18"
rolling = "23"

[alias.java.versions]
lts = "corretto-21"
rolling = "corretto-24"

[tools]
# Pre-reqs
cosign = "latest"
usage = "latest"
uv = "latest"
"asdf:dotnet" = "latest"
"ubi:tectonic-typesetting/tectonic" = { version = "tectonic@0.15.0", exe = "tectonic" }
"vfox:cmake" = "latest"
"vfox:kotlin" = "latest"
bat = "latest"
bitwarden = "latest"
bottom = "latest"
bun = "latest"
delta = "latest"
deno = "latest"
dotenv-linter = "latest"
editorconfig-checker = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
java = "lts"
julia = "latest"
lazygit = "latest"
node = "lts"
openbao = "latest"
opentofu = "latest"
packer = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
shellcheck = "latest"
terraform = "latest"
typst = "latest"
zig = "latest"
neovim = "stable"
tmux = "latest"
aws-cli = "latest"
tree-sitter = "latest"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:aws-cdk" = "latest"
"npm:commitlint-format-json" = "latest"
"npm:eslint" = "latest"
"npm:eslint-config-prettier" = "latest"
"npm:eslint-plugin-prettier" = "latest"
"npm:license-report" = "latest"
"npm:prettier" = "latest"
"npm:stylelint" = "latest"
"npm:stylelint-prettier" = "latest"
"npm:typescript" = "latest"
"npm:wsl-open" = "latest"
"npm:lua-3p-language-servers" = "latest"
