---
extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  comments:
    level: error
  comments-indentation:
    level: error
  empty-values: enable
  float-values:
    require-numeral-before-decimal: true
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: true
  key-ordering: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  octal-values:
    forbid-implicit-octal: true
  quoted-strings:
    required: only-when-needed
  truthy:
    level: error
