---
formatter:
  type: basic
  indent: 2
  include_document_start: true
  line_ending: lf
  retain_line_breaks: true
  max_line_length: 0
  pad_line_comments: 2
  trim_trailing_whitespace: true
  eof_newline: true
