[colors]
ansi = [
  "#0d0c0c",
  "#c4746e",
  "#8a9a7b",
  "#c4b28a",
  "#8ba4b0",
  "#a292a3",
  "#8ea4a2",
  "#c8c093",
]
brights = [
  "#a6a69c",
  "#e46876",
  "#87a987",
  "#e6c384",
  "#7fb4ca",
  "#938aa9",
  "#7aa89f",
  "#181616",
]
background = "#181616"
foreground = "#c5c9c5"
cursor_bg = "#c8c093"
cursor_fg = "#181616"
cursor_border = "#c8c093"
selection_fg = "#c8c093"
selection_bg = "#2d4f67"
scrollbar_thumb = "#16161d"
split = "#16161d"

[colors.indexed]
16 = "#ffa066"
17 = "#ff5d6c"

[metadata]
name = "Kanagawa-Dragon"
wezterm_version = "20230320-124340-559cb7b0"
