#!/usr/bin/env bash

TMUX_PLUGIN_MANAGER_PATH="$HOME/.config/tmux/plugins"

# Download the tmux plugin manager if it isn't already there
if [[ ! -d "$TMUX_PLUGIN_MANAGER_PATH/tpm" ]]; then
  git clone https://github.com/tmux-plugins/tpm "$TMUX_PLUGIN_MANAGER_PATH/tpm"
fi

if [[ -f "$TMUX_PLUGIN_MANAGER_PATH/tpm/bin/install_plugins" ]]; then
  "$TMUX_PLUGIN_MANAGER_PATH/tpm/bin/install_plugins"
fi
