#!/usr/bin/env bash

# Download vim-plug & initialize the bundles
if [[ ! -e $HOME/.vim/autoload/plug.vim ]]; then
  curl -fsSLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim -u $HOME/.vimrc.bundles +PlugInstall +PlugClean! +qa

# Create the scratch directories
mkdir -p $HOME/.vimscratch/backup
mkdir -p $HOME/.vimscratch/swap
mkdir -p $HOME/.vimscratch/undo
