#!/usr/bin/env bash

# Download vim-plug & initialize the bundles
if [[ ! -e $HOME/.vim/autoload/plug.vim ]]; then
  curl -fsSLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [[ -f $HOME/.vim/vimrc.bundles ]]; then
    vim -u $HOME/.vim/vimrc.bundles +PlugInstall +PlugClean! +qa -
fi

# Create the scratch directories
mkdir -p $HOME/.vim/vimscratch/backup
mkdir -p $HOME/.vim/vimscratch/swap
mkdir -p $HOME/.vim/vimscratch/undo

