#!/usr/bin/env bash

printf "\e[0;30mBlack - \e[1;30mBold Black - \e[0;90mHigh intensity Black - \e[1;90mBold High intensity Black\n"
printf "\e[0;31mRed - \e[1;31mBold Red - \e[0;91mHigh intensity Red - \e[1;91mBold High intensity Red\n"
printf "\e[0;32mGreen - \e[1;32mBold Green - \e[0;92mHigh intensity Green - \e[1;92mBold High intensity Green\n"
printf "\e[0;33mYellow - \e[1;33mBold Yellow - \e[0;93mHigh intensity Yellow - \e[1;93mBold High intensity Yellow\n"
printf "\e[0;34mBlue - \e[1;34mBold Blue - \e[0;94mHigh intensity Blue - \e[1;94mBold High intensity Blue\n"
printf "\e[0;35mPurple - \e[1;35mBold Purple - \e[0;95mHigh intensity Purple - \e[1;95mBold High intensity Purple\n"
printf "\e[0;36mCyan - \e[1;36mBold Cyan - \e[0;96mHigh intensity Cyan - \e[1;96mBold High intensity Cyan\n"
printf "\e[0;37mWhite - \e[1;37mBold White - \e[0;97mHigh intensity White - \e[1;97mBold High intensity White\n"
