local M = {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPost", "BufNewFile" },
  build = ":TSUpdate",
}

function M.config()
  require("nvim-treesitter.configs").setup({
    ensure_installed = {
      "bash",
      "bibtex",
      "c",
      "c_sharp",
      "cmake",
      "comment",
      "cooklang",
      "cpp",
      "css",
      "csv",
      "diff",
      "dockerfile",
      "editorconfig",
      "fortran",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gpg",
      "graphql",
      "hcl",
      "html",
      "ini",
      "java",
      "javascript",
      "jq",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "kotlin",
      "latex",
      "ledger",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "mermaid",
      "pascal",
      "passwd",
      "perl",
      "php",
      "phpdoc",
      "powershell",
      "printf",
      "python",
      "query",
      "readline",
      "regex",
      "robots",
      "ruby",
      "rust",
      "scss",
      "sql",
      "ssh_config",
      "svelte",
      "terraform",
      "tmux",
      "todotxt",
      "toml",
      "tsv",
      "tsx",
      "typescript",
      "typst",
      "vim",
      "vimdoc",
      "vue",
      "xml",
      "yaml",
    },
    sync_install = true,
    auto_installed = true,
    highlight = { enable = true },
    indent = { enable = true },
  })

  -- Mappings
  local wk = require("which-key")
  wk.add({
    { "<leader>T", group = "Treesitter" },
  })
end

return M
