#!/usr/bin/env bash
# ~/.bash_logout: executed by bash(1) when login shell exits.

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
  [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

# dotfiles="${DOTFILES:-$(xdg-user-dir DOTFILES)}"
# dotfiles="${dotfiles:-${HOME}/.dotfiles}"
# profile_path="${PROFILEPATH:-$(xdg-user-dir PROFILE)}"
# profile_path="${profile_path:-${HOME}/profile}"

# Unmount the shares
# if mountpoint -q "${profile_path}/mounts/files"; then
#   [[ -x "${dotfiles}/bin/moose-unmount-shares" ]] && "${dotfiles}/bin/moose-unmount-shares"
# fi

# unset dotfiles
# unset profile_path
