#!/usr/bin/env bash

# If not running interactively, don't do anything
if [[ "$-" != *i* ]]; then
    return
fi

export DOTFILES="$HOME/.dotfiles"
export DOTFILES_PRIVATE="$HOME/.dotfiles-private"

source "$DOTFILES/bash/base-colors.bash"
source "$DOTFILES/bash/base-functions.bash"
source "$DOTFILES/bash/base-symbols.bash"

SetOsEnvironmentVariables
SetVirtualizationEnvironmentVariables

# Loop in $DOTFILES first, then $DOTFILES_PRIVATE
for root in "$DOTFILES/bash" "$DOTFILES_PRIVATE/bash"; do
    # Loop in a shared folder, then OS specific, lastly distro specific for Linux
    for base in "shared" "$OS_PRIMARY" "distros/$OS_SECONDARY"; do
        # Options file should be first
        source_if "$root/$base/options.bash"

        # Loop over functions and completions to include
        for folder in "exports" "functions" "third-party" "other" "aliases"; do
            if [[ -d "$root/$base/$folder" ]]; then
                for file in "$root/$base/$folder/*.bash"; do
                    source_if "$file"
                done
            fi
        done
    done
done

# On Windows shells runnin in WSL run some overrides
if [[ $IS_WSL == "true" ]]; then
    for root in "$DOTFILES/bash" "$DOTFILES_PRIVATE/bash"; do
        # Options file should be first
        source_if "$root/windows-wsl/options.bash"

        # Loop over functions and completions to include
        for folder in "exports" "functions" "third-party" "other" "aliases"; do
            if [[ -d "$root/windows-wsl/$folder" ]]; then
                for file in "$root/windows-wsl/$folder/*.bash"; do
                    source_if "$file"
                done
            fi
        done
    done
fi

# Local config, this should be last and never checked into source control (or if it is it should be host specific)
source_if "$HOME/.bashrc.local"

unset root
unset base
unset folder
unset file

