local utils = require("core.utils")

utils.plugin("plugins.alpha")
utils.plugin("plugins.breadcrumbs")
utils.plugin("plugins.cmp")
utils.plugin("plugins.comment")
utils.plugin("plugins.copy-file-path")
utils.plugin("plugins.dap")
utils.plugin("plugins.devicons")
utils.plugin("plugins.formatting")
utils.plugin("plugins.gitsigns")
utils.plugin("plugins.harpoon")
utils.plugin("plugins.hop")
utils.plugin("plugins.illuminate")
utils.plugin("plugins.indentline")
utils.plugin("plugins.linting")
utils.plugin("plugins.lspconfig")
utils.plugin("plugins.lualine")
utils.plugin("plugins.markdown-preview")
utils.plugin("plugins.mason")
utils.plugin("plugins.navic")
utils.plugin("plugins.neogit")
utils.plugin("plugins.neotest")
utils.plugin("plugins.nvim-tmux-navigation")
utils.plugin("plugins.nvimtree")
utils.plugin("plugins.obsidian")
utils.plugin("plugins.oncedark")
-- utils.plugin("plugins.onedarkpro")
utils.plugin("plugins.project")
utils.plugin("plugins.rainbow-delimiters")
utils.plugin("plugins.schemastore")
utils.plugin("plugins.surround")
utils.plugin("plugins.telescope")
utils.plugin("plugins.todo-comments")
utils.plugin("plugins.toggleterm")
utils.plugin("plugins.treesitter")
utils.plugin("plugins.trouble")
utils.plugin("plugins.whichkey")

-- Extras: These are plugins that are either non-critical or I haven't
-- fully decided to make them permanent yet.
utils.plugin("plugins.extras.bqf")
utils.plugin("plugins.extras.colorizer")
utils.plugin("plugins.extras.cutlass")
utils.plugin("plugins.extras.dressing")
utils.plugin("plugins.extras.gitlinker")
utils.plugin("plugins.extras.lab")
utils.plugin("plugins.extras.modicator")
utils.plugin("plugins.extras.noice")
utils.plugin("plugins.extras.oil")
utils.plugin("plugins.extras.tabby")
-- utils.plugin("plugins.extras.tabnine")
-- utils.plugin("plugins.extras.ufo")

-- Vim: These are old (non-Lua) vim plugins, if native alternatives can be found
-- I should switch to those
utils.plugin("plugins.vim.repeat")
